FROM amazon/aws-cli:2.0.33

ENV PATH="/go/bin:${PATH}"

WORKDIR /go/src
COPY . .
RUN yum install -y go \
    && mkdir -p /go/bin \
    && go build -o /go/bin/filesyncer \
    && rm -rf /go/src/*

ENTRYPOINT ["filesyncer"]
