ARG CONTAINER_TAG=latest
ARG BASE_CONTAINER=onepanel/tensorflow-gpu:$CONTAINER_TAG
FROM $BASE_CONTAINER

LABEL maintainer="Onepanel, Inc. <support@onepanel.io>"

#Do not switch out root user, want to run as root.
USER root

RUN pip3 --no-cache-dir install torch torchvision && \
    npm cache clean --force && \
    rm -rf "/home/${NB_USER}/.cache/yarn" && \
    rm -rf "/home/${NB_USER}/.node-gyp" && \
    fix-permissions "/home/${NB_USER}"



