ARG CONTAINER_TAG=latest
ARG BASE_CONTAINER=onepanel/opencv-base:$CONTAINER_TAG
FROM $BASE_CONTAINER

LABEL maintainer="Onepanel, Inc. <support@onepanel.io>"

#Do not switch out root user, want to run as root.
USER root
COPY keyboard.conf keyboard.conf
COPY tf_configure.bazelrc /home/root/.tf_configure.bazelrc

ARG TENSORFLOW_VERSION=r2.3.0
ENV TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.0
ENV TF_NEED_CUDA 1
ENV PYTHON_BIN_PATH="/usr/bin/python3"

RUN DEBIAN_FRONTEND=noninteractive sudo apt update && \
    sudo apt install -y debconf-utils python3-dev python3-pip python3-setuptools && \
    debconf-set-selections < keyboard.conf && \
    sudo apt-get install -y software-properties-common vim && \
    /usr/bin/pip3 --no-cache-dir install -U pip six 'numpy<1.19.0' wheel setuptools mock 'future>=0.17.1' && \
    /usr/bin/pip3 --no-cache-dir install -U keras_applications --no-deps && \
    /usr/bin/pip3 --no-cache-dir install -U keras_preprocessing --no-deps && \
    wget https://github.com/bazelbuild/bazelisk/releases/download/v1.5.0/bazelisk-linux-amd64 && \
    mv bazelisk-linux-amd64 /usr/local/bin/bazel && \
    chmod a+x /usr/local/bin/bazel && \
    git clone https://github.com/tensorflow/tensorflow.git && \
    cd tensorflow && \
    git checkout r2.3 && \
    cp /home/root/.tf_configure.bazelrc ./.tf_configure.bazelrc && \
    bazel build //tensorflow/tools/pip_package:build_pip_package && \
    ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg && \
    /usr/bin/pip3 --no-cache-dir install /tmp/tensorflow_pkg/*.whl && \
    pip3 --no-cache-dir install /tmp/tensorflow_pkg/*.whl && \
    cd /home/root && \
    rm -rf /home/root/tensorflow && \
    rm -rf /tmp/* && \
    rm -rf /home/root/.cache/* && \
    npm cache clean --force && \
    rm -rf "/home/${NB_USER}/.cache/yarn" && \
    rm -rf "/home/${NB_USER}/.node-gyp" && \
    fix-permissions "/home/${NB_USER}" && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apt/archives/*
