ARG BASE_CONTAINER=onepanel/jupyterlab-base
FROM $BASE_CONTAINER

LABEL maintainer="OnepanelIO <aleksandr@onepanel.io>"

#Do not switch out root user, want to run as root.
USER root

RUN pip install torch torchvision tensorflow && \
    npm cache clean --force && \
    rm -rf "/home/${NB_USER}/.cache/yarn" && \
    rm -rf "/home/${NB_USER}/.node-gyp" && \
    fix-permissions "/home/${NB_USER}"



