ARG CONTAINER_TAG=latest
ARG BASE_CONTAINER=onepanel/minimal-notebook:$CONTAINER_TAG
FROM $BASE_CONTAINER

LABEL maintainer="Onepanel, Inc. <support@onepanel.io>"

USER root

# Script to install the NodeSource Node.js 12.x LTS
# repo onto a Debian or Ubuntu system.
# https://github.com/nodesource/distributions#debinstall
RUN curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && \
    apt-get update && \
    # ffmpeg for matplotlib anim & dvipng for latex labels
    apt-get install -y --no-install-recommends ffmpeg dvipng \
            supervisor \
            binutils \
            nodejs \
            lua5.1 \
            nginx \
            graphviz \
            axel \
            imagemagick \
      && apt-get clean \
      && apt-get autoremove \
      && rm -rf /var/cache/apt/archives/* \
      && rm -rf /var/lib/apt/lists/*

USER $NB_UID

RUN conda install xeus-python -c conda-forge && \
    pip3 --no-cache-dir install \
    'jupyter-lsp' \
    'beautifulsoup4==4.9.*' \
    'bokeh==2.1.*' \
    'bottleneck==1.3.*' \
    'cloudpickle==1.5.*' \
    'cython==0.29.*' \
    'dask==2.20.*' \
    'dill==0.3.*' \
    'h5py==2.10.*' \
    'ipywidgets==7.5.*' \
    'ipympl==0.5.*'\
    'matplotlib' \
    # numba update to 0.49 fails resolving deps.
    'numba==0.48.*' \
    'numexpr==2.7.*' \
    'pandas==1.0.*' \
    'patsy==0.5.*' \
    'protobuf==3.12.*' \
    'tables==3.6.*' \
    'scikit-image==0.17.*' \
    'scikit-learn==0.23.*' \
    'scipy==1.5.*' \
    'seaborn==0.10.*' \
    'sqlalchemy==1.3.*' \
    'statsmodels==0.11.*' \
    'sympy==1.6.*' \
    'vincent==0.4.*' \
    'widgetsnbextension==3.5.*'\
    'xlrd==1.2.*' \
    && \
    # Activate ipywidgets extension in the environment that runs the notebook server
    jupyter nbextension enable --py widgetsnbextension --sys-prefix && \
    # Also activate ipywidgets extension for JupyterLab
    # Check this URL for most recent compatibilities
    # https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager
    jupyter labextension install @jupyter-widgets/jupyterlab-manager@^2.0.0 --no-build && \
    jupyter labextension install @bokeh/jupyter_bokeh@^2.0.0 --no-build && \
    jupyter labextension install jupyter-matplotlib@^0.7.2 --no-build && \
    jupyter lab build -y && \
    jupyter lab clean -y && \
    npm cache clean --force && \
    rm -rf "/home/${NB_USER}/.cache/yarn" && \
    rm -rf "/home/${NB_USER}/.node-gyp" && \
    fix-permissions "/home/${NB_USER}"

# Install facets which does not have a pip or conda package at the moment
WORKDIR /tmp
RUN git clone https://github.com/PAIR-code/facets.git && \
    jupyter nbextension install facets/facets-dist/ --sys-prefix && \
    rm -rf /tmp/facets && \
    fix-permissions "/home/${NB_USER}"

# Import matplotlib the first time to build the font cache.
ENV XDG_CACHE_HOME="/home/${NB_USER}/.cache/"

RUN python3 -c "import matplotlib.pyplot" && \
    fix-permissions "/home/${NB_USER}"

USER $NB_UID

WORKDIR $HOME
