ARG CONTAINER_TAG=latest
ARG BASE_CONTAINER=onepanel/jupyterlab-base:$CONTAINER_TAG
FROM $BASE_CONTAINER

LABEL maintainer="OnepanelIO <aleksandr@onepanel.io>"

#Do not switch out root user, want to run as root.
USER root
# todo run apt clean
COPY keyboard.conf keyboard.conf

ARG TENSORFLOW_VERSION=r2.3.0
ENV TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.0
ENV TF_NEED_CUDA 1

RUN DEBIAN_FRONTEND=noninteractive sudo apt update && \
    sudo apt install -y debconf-utils python3-dev python3-pip && \
    debconf-set-selections < keyboard.conf && \
    sudo apt-get install -y software-properties-common vim && \
    pip3 install -U pip six 'numpy<1.19.0' wheel setuptools mock 'future>=0.17.1' && \
    pip3 install -U keras_applications --no-deps && \
    pip3 install -U keras_preprocessing --no-deps && \
    wget https://github.com/bazelbuild/bazelisk/releases/download/v1.5.0/bazelisk-linux-amd64 && \
    mv bazelisk-linux-amd64 /usr/local/bin/bazel && \
    chmod a+x /usr/local/bin/bazel && \
    git clone https://github.com/tensorflow/tensorflow.git && \
    cd tensorflow && \
    npm cache clean --force && \
    rm -rf "/home/${NB_USER}/.cache/yarn" && \
    rm -rf "/home/${NB_USER}/.node-gyp" && \
    fix-permissions "/home/${NB_USER}"