ARG CONTAINER_TAG=latest
ARG BASE_CONTAINER=onepanel/scipy-notebook:$CONTAINER_TAG
FROM $BASE_CONTAINER

LABEL maintainer="OnepanelIO <aleksandr@onepanel.io>"

#Do not switch out root user, want to run as root.
USER root

RUN pip3 --no-cache-dir install --upgrade jupyterlab-git && \
    pip3 --no-cache-dir install --upgrade nbdime && \
    pip3 --no-cache-dir install --upgrade tensorboard && \
    jupyter labextension install @jupyterlab/github && \
    jupyter labextension install @jupyterlab/debugger && \
    jupyter lab build -y && \
    jupyter lab clean -y && \
    npm cache clean --force && \
    rm -rf "/home/${NB_USER}/.cache/yarn" && \
    rm -rf "/home/${NB_USER}/.node-gyp" && \
    fix-permissions "/home/${NB_USER}"
